/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
**                   Auther: brinkqiang                            **
********************************************************************/
// source: interface.pkg

#ifndef __INTERFACE_SOL_H__
#define __INTERFACE_SOL_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "lua.h"
#include "lualib.h"
#include "lauxlib.h"

LUA_API int luaopen_interface(lua_State* L);
LUA_API int require_interface(lua_State* L);

#ifdef __cplusplus
}
#endif

#endif  // __INTERFACE_SOL_H__
